// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn1YNDCUg-WwVOpjcvY7I7Kwhmy7zOj40',
    appId: '1:454721064468:web:225d5814122bf1046c2101',
    messagingSenderId: '454721064468',
    projectId: 'budgiemate-2',
    authDomain: 'budgiemate-2.firebaseapp.com',
    storageBucket: 'budgiemate-2.firebasestorage.app',
    measurementId: 'G-WYZP7VMFYW',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6FQLTrs4uGHo2Zb2hJ4pusxUWiGCbjY8',
    appId: '1:454721064468:ios:083c4e89f9a9ddb56c2101',
    messagingSenderId: '454721064468',
    projectId: 'budgiemate-2',
    storageBucket: 'budgiemate-2.firebasestorage.app',
    iosBundleId: 'com.example.budgiemate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAn1YNDCUg-WwVOpjcvY7I7Kwhmy7zOj40',
    appId: '1:454721064468:web:bb651b0d0da34f8c6c2101',
    messagingSenderId: '454721064468',
    projectId: 'budgiemate-2',
    authDomain: 'budgiemate-2.firebaseapp.com',
    storageBucket: 'budgiemate-2.firebasestorage.app',
    measurementId: 'G-WEHMQKWPG0',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6FQLTrs4uGHo2Zb2hJ4pusxUWiGCbjY8',
    appId: '1:454721064468:ios:083c4e89f9a9ddb56c2101',
    messagingSenderId: '454721064468',
    projectId: 'budgiemate-2',
    storageBucket: 'budgiemate-2.firebasestorage.app',
    iosBundleId: 'com.example.budgiemate',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAEjYgulIgHMpyhKmQ8psKZ8Uj5OF-3qA',
    appId: '1:454721064468:android:9c1a1bc991f2b9cc6c2101',
    messagingSenderId: '454721064468',
    projectId: 'budgiemate-2',
    storageBucket: 'budgiemate-2.firebasestorage.app',
  );

}